### ISSUE TITLE
clear all finished downloads button

### ISSUE THREAD

**Issue by mythodeia** [JamesCoyle/DownloadsExtension#10]
Hello James

I was looking the other day for a download manager and I tried your extension in my Brave browser. 
I am super happy with it. It does what it supposed to do without any bells and whistles. :)
Great work !!!

The only thing I would add is a button to clear all downloads. You could add it right next to the settings icon on the top right.
Anyway, its just a suggestion as I have an OCD and I like to clear all my downloads without doing it one be one. :P 

Thanks a lot for your work

**Comment by JamesCoyle** [comment]
Hi, thanks for downloading!

This isn't really something I want to look at implementing at the moment as it gets complicated regarding what action should be taken for downloads that are currently in progress. I would need to figure out the best way to handle that situation with such a small UI. I'll keep it on the list for future updates though.

**Comment by JamesCoyle** [comment]
For now you should be able to go to chrome://downloads (or click manage downloads in the extension), click the three dots in the top right, and then click clear all. It doesn't always seem to clear the downloads from the popup instantly though.

**Comment by ZachSaucier** [comment]
Given you're able to show the loading state it shouldn't be too hard to keep a list of which downloads are currently in progress. Then use that list vs the "full" list when the delete all button is clicked.
