### ISSUE TITLE
Suggestion for enhancement: more notification options

### ISSUE THREAD

**Issue by oep42** [JamesCoyle/DownloadsExtension#12]
Currently, in the settings, there are options to notify on complete and to notify on error.

I would suggest the following addition to the settings:
--- Option to notify when a download starts.
--- For each option to notify: add an option to set the duration of the notification in seconds (including an option that the notification remains visible on screen until the user dismisses the notification [which may especially be useful when an error occurs]).

**Comment by JamesCoyle** [comment]
I have now implemented notifications for starting, paused, error, and complete states in the latest v3 release. These can be individually enabled in the settings. The error notification should remain on screen until interacted with.
