### ISSUE TITLE
Link to repo and issue tracker in settings UI

### ISSUE THREAD

**Issue by janosh** [JamesCoyle/DownloadsExtension#13]
I think the settings UI would benefit from links to this repo and its issue tracker to make it easier to suggest improvements.

<img src="https://user-images.githubusercontent.com/30958850/147329060-de3f6eb3-a093-49cd-8b4a-416d3595214a.png" width="600">

Also, why the spelling `downloads-extention` rather than extension?

**Comment by JamesCoyle** [comment]
Good Idea! I have added an information page with this repo linked. Should be out in v2.3.0 once it has passed review.
