### ISSUE TITLE
Can't download large files in Chrome

### ISSUE THREAD

**Issue by Mizamook** [JamesCoyle/DownloadsExtension#16]
Have to use Firefox to download large files.  Chrome and Opera both fail the downloads (anything over 5ooMB)

**Comment by JamesCoyle** [comment]
Do you have a link to the files you are trying to download?

**Comment by Mizamook** [comment]
One is Davinci Resolve (pro version)  .. it's a license/private link, but
possible here for the free one:
https://www.blackmagicdesign.com/products/davinciresolve/

Others are Google drive videos (not shareable).

Others are pretty much any large file.  Small files are fine.

Issue with Chrome was not downloading stuff ("Failed: Network Error") I
thought a download manager would help.  As far as I can see, it does
nothing .. I have to use Firefox. (and I don't have problems with Firefox
download of the same files)

Thanks!

**Comment by JamesCoyle** [comment]
I can't seem to reproduce the issue on my end so I suspect there is something going on with your system. This extension only provides an alternative UI to the default browser download UI so I'm not doing anything different in the backend to download files. 

Perhaps you can try reinstalling the browsers which don't work correctly? I'm sorry I can't be of more help.
