### ISSUE TITLE
Notifications not work

### ISSUE THREAD

**Issue by LeninEnisey** [JamesCoyle/DownloadsExtension#18]
Hello!
Notifications not work.
[https://youtu.be/yGHt4sw2WSM](url)

**Comment by uDEV2019** [comment]
@LeninEnisey Under Chromium (ungoogled) i can't reproduce this behaviour, but its weird anyway...
Activating an option, nothing happens. Leaving and re-entering the settings dialog, the activated options are still activated.
Deactivating an option you will be asked to allow or disallow the permission for notifications.
