### ISSUE TITLE
Icon is always blue at start

### ISSUE THREAD

**Issue by IvoryJam** [JamesCoyle/DownloadsExtension#19]
The icon is always blue at start for me, I have to toggle the drop down before it will go back to the theme I set.

This happens on a set color as well as "match theme"

Extension version: 3.0.0
Chromium Version: 100.0.4896.79
Brave Version: 1.38.80

**Comment by JamesCoyle** [comment]
I think I introduced a race condition where the saved settings sometimes do not override the default settings. Will get this fixed in the next update.

**Comment by JamesCoyle** [comment]
@IvoryJam The latest update v3.0.1 includes a fix for this issue. Can you check you have this latest version and verify that it has fixed the issue please?

**Comment by IvoryJam** [comment]
Now it just stays blue, double checked my settings and it's set to dark gray. If I toggle that then it'll set the correct color until next time I start Brave

**Comment by JamesCoyle** [comment]
Version 3.1.1 should be going out soon which will hopefully fix this issue properly. v3.1 now lets you specify a custom icon color too cause I figured I might as well while looking into this issue. Let me know if the fix works once it goes live.

**Comment by IvoryJam** [comment]
Confirmed it once Google Store updated. Great work and thank you!

**Comment by JamesCoyle** [comment]
Awesome! Thanks for your help identifying this issue.
