### ISSUE TITLE
Options badge text

### ISSUE THREAD

**Issue by Explosion-Scratch** [JamesCoyle/DownloadsExtension#21]
This could be percentage done overall, number of downloads, or even a scrolling title of the current file

**Comment by JamesCoyle** [comment]
Great suggestion but unfortunately this wouldn't be possible as the background process has no way to detect the percentage completion of downloads.

**Comment by Explosion-Scratch** [comment]
Wait can't you just do this with the chrome.downloads API? Is it not implemented or is it impossible?

**Comment by JamesCoyle** [comment]
The API doesn't provide an event to track the download progress. I can track the progress in the popup by fetching the downloads continuously but this doesn't work in the service worker as there is no guarantee that it will be active while the download occurs. It's dumb that there is no progress event...

**Comment by Explosion-Scratch** [comment]
> The API doesn't provide an event to track the download progress. I can track the progress in the popup by fetching the downloads continuously but this doesn't work in the service worker as there is no guarantee that it will be active while the download occurs. It's dumb that there is no progress event...

Ohh, I forgot about service workers auto shutting down

**Comment by Explosion-Scratch** [comment]
Would it be possible with chrome.alarms + periodic fetching?

**Comment by JamesCoyle** [comment]
Alarms can only trigger once a minute at the fastest so it wouldn't be very accurate.

**Comment by Explosion-Scratch** [comment]
Oh, didn't know that, ok
